//! # Redis to PostgreSQL Sync Library
//!
//! This library provides functionality to sync blockchain events from Redis streams
//! (generated by rindexer) to PostgreSQL for advanced analytics and querying.
//!
//! ## Overview
//!
//! The library consists of simplified modules:
//! - **Config**: Single configuration module for all settings
//! - **Core**: Core types, pipeline orchestration, and circuit breaker
//! - **Consumer**: Redis stream consumer with message parsing
//! - **Sync**: PostgreSQL synchronization
//! - **Monitoring**: Simplified metrics collection
//! - **Error**: Centralized error handling
//! - **HTTP Server**: Health checks and metrics endpoints

pub mod config;
pub mod core;
pub mod consumer;
pub mod sync;
pub mod monitoring;
pub mod error;
pub mod http_server;
pub mod processors;

// Re-export main types for convenience
pub use config::Config;
pub use core::types::{RindexerEvent, TransactionInformation, StreamMessage, PipelineHealth};
pub use core::pipeline::EventProcessingPipeline;
pub use core::circuit_breaker::CircuitBreaker;
pub use monitoring::metrics::{Metrics, MetricsSnapshot};
pub use error::{SyncError, Result};
pub use http_server::HttpServer;

/// Current version of the library
pub const VERSION: &str = env!("CARGO_PKG_VERSION");
