//! # Redis to SurrealDB Sync Library
//!
//! This library provides functionality to sync blockchain events from Redis streams
//! (generated by rindexer) to SurrealDB for advanced analytics and querying.
//!
//! ## Overview
//!
//! The library consists of simplified modules:
//! - **Config**: Single configuration module for all settings
//! - **Core**: Core types, pipeline orchestration, and circuit breaker
//! - **Consumer**: Redis stream consumer with message parsing
//! - **Sync**: SurrealDB synchronization
//! - **Monitoring**: Simplified metrics collection
//! - **Error**: Centralized error handling
//! - **HTTP Server**: Health checks and metrics endpoints

pub mod config;
pub mod consumer;
pub mod core;
pub mod error;
pub mod http_server;
pub mod monitoring;
pub mod sync;

// Re-export main types for convenience
pub use config::Config;
pub use core::circuit_breaker::CircuitBreaker;
pub use core::pipeline::EventProcessingPipeline;
pub use core::types::{PipelineHealth, RindexerEvent, StreamMessage, TransactionInformation};
pub use error::{Result, SyncError};
pub use http_server::HttpServer;
pub use monitoring::metrics::{Metrics, MetricsSnapshot};

/// Current version of the library
pub const VERSION: &str = env!("CARGO_PKG_VERSION");
