global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Redis Surreal Sync application metrics
  - job_name: 'redis-surreal-sync'
    static_configs:
      - targets: ['redis-surreal-sync:8080']
    scrape_interval: 5s
    metrics_path: /metrics
    scrape_timeout: 5s


  # SurrealDB metrics (if exposed)
  - job_name: 'surrealdb'
    static_configs:
      - targets: ['surrealdb:8000']
    scrape_interval: 30s
    metrics_path: /health
    scrape_timeout: 10s
