groups:
  - name: redis_postgres_sync_event_type_alerts
    interval: 15s
    rules:
      # Critical: Nearly all events of a specific type are failing
      - alert: AllEventsFailingForType
        expr: redis_postgres_sync:failure_rate_percent:by_type > 95
        for: 2m
        labels:
          severity: critical
          component: redis-postgres-sync
        annotations:
          summary: "Nearly all {{ $labels.event_type }} events are failing"
          description: "{{ $labels.event_type }} events have a {{ $value | humanizePercentage }} failure rate for over 2 minutes. This indicates a critical issue with processing this event type."
          runbook_url: "https://github.com/0xIntuition/research-surreal/blob/main/docs/runbooks/event-type-failures.md"

      # Warning: Elevated failure rate for a specific event type
      - alert: HighEventTypeFailureRate
        expr: redis_postgres_sync:failure_rate_percent:by_type > 5
        for: 5m
        labels:
          severity: warning
          component: redis-postgres-sync
        annotations:
          summary: "High failure rate for {{ $labels.event_type }} events"
          description: "{{ $labels.event_type }} events have a {{ $value | humanizePercentage }} failure rate for over 5 minutes. Normal failure rate should be near 0%."
          runbook_url: "https://github.com/0xIntuition/research-surreal/blob/main/docs/runbooks/event-type-failures.md"

      # Warning: Event type processing is slow
      - alert: SlowEventTypeProcessing
        expr: redis_postgres_sync:event_processing_duration_seconds:p95:by_type > 5
        for: 5m
        labels:
          severity: warning
          component: redis-postgres-sync
        annotations:
          summary: "Slow processing for {{ $labels.event_type }} events"
          description: "95th percentile processing time for {{ $labels.event_type }} events is {{ $value | humanizeDuration }} (over 5 seconds) for the last 5 minutes."
          runbook_url: "https://github.com/0xIntuition/research-surreal/blob/main/docs/runbooks/slow-event-processing.md"

      # Warning: Cascade processing is slow for a specific event type
      - alert: SlowCascadeProcessing
        expr: redis_postgres_sync:cascade_duration_seconds:p95:by_type > 2
        for: 5m
        labels:
          severity: warning
          component: redis-postgres-sync
        annotations:
          summary: "Slow cascade processing for {{ $labels.event_type }} events"
          description: "95th percentile cascade time for {{ $labels.event_type }} events is {{ $value | humanizeDuration }} (over 2 seconds) for the last 5 minutes. This may indicate database performance issues."
          runbook_url: "https://github.com/0xIntuition/research-surreal/blob/main/docs/runbooks/slow-cascade-processing.md"

      # Info: No events of a specific type have been processed recently
      - alert: NoEventsProcessedForType
        expr: rate(redis_postgres_sync_events_processed_by_type_total[10m]) == 0
        for: 10m
        labels:
          severity: info
          component: redis-postgres-sync
        annotations:
          summary: "No {{ $labels.event_type }} events processed recently"
          description: "No {{ $labels.event_type }} events have been processed in the last 10 minutes. This may be expected if this event type is rare."
          runbook_url: "https://github.com/0xIntuition/research-surreal/blob/main/docs/runbooks/no-events.md"

      # Info: Unusual spike in database operations
      - alert: DatabaseOperationSpike
        expr: |
          redis_postgres_sync:database_operations_rate:by_type
          >
          2 * avg_over_time(redis_postgres_sync:database_operations_rate:by_type[1h])
        for: 5m
        labels:
          severity: info
          component: redis-postgres-sync
        annotations:
          summary: "Spike in {{ $labels.operation }} operations for {{ $labels.event_type }}"
          description: "Database operation rate for {{ $labels.operation }} ({{ $labels.event_type }}) is {{ $value | humanize }} ops/sec, which is 2x the 1-hour average."
          runbook_url: "https://github.com/0xIntuition/research-surreal/blob/main/docs/runbooks/database-spike.md"
