## Alert Rules for PostgreSQL Writer Service
##
## Threshold Rationale:
## - SlowEventTypeProcessing (P95 > 5s): Based on expected database transaction times.
##   Blockchain events should process quickly (<1s typical). 5s threshold allows for
##   occasional database contention while catching sustained performance degradation.
##
## - SlowCascadeProcessing (P95 > 2s): Cascade updates involve multiple aggregation
##   queries. 2s threshold is chosen as cascade operations should be faster than full
##   event processing, while accounting for complex triple/vault aggregations.
##
## - DatabaseOperationSpike (2x 1-hour average): Detects unusual activity patterns
##   that might indicate runaway cascades, retry loops, or unexpected event volumes.
##   2x multiplier reduces false positives from normal traffic fluctuations.
##
## - HighEventTypeFailureRate (>5%): Normal operation should have near-zero failures.
##   5% allows for transient issues while catching persistent problems early.
##
groups:
  - name: postgres_writer_event_type_alerts
    interval: 15s
    rules:
      # Critical: Nearly all events of a specific type are failing
      - alert: AllEventsFailingForType
        expr: postgres_writer:failure_rate_percent:by_type > 95
        for: 2m
        labels:
          severity: critical
          component: postgres-writer
        annotations:
          summary: "Nearly all {{ $labels.event_type }} events are failing"
          description: "{{ $labels.event_type }} events have a {{ $value | humanizePercentage }} failure rate for over 2 minutes. This indicates a critical issue with processing this event type."
          runbook_url: "https://github.com/0xIntuition/research-surreal/blob/main/docs/runbooks/event-type-failures.md"

      # Warning: Elevated failure rate for a specific event type
      - alert: HighEventTypeFailureRate
        expr: postgres_writer:failure_rate_percent:by_type > 5
        for: 5m
        labels:
          severity: warning
          component: postgres-writer
        annotations:
          summary: "High failure rate for {{ $labels.event_type }} events"
          description: "{{ $labels.event_type }} events have a {{ $value | humanizePercentage }} failure rate for over 5 minutes. Normal failure rate should be near 0%."
          runbook_url: "https://github.com/0xIntuition/research-surreal/blob/main/docs/runbooks/event-type-failures.md"

      # Warning: Event type processing is slow
      - alert: SlowEventTypeProcessing
        expr: postgres_writer:event_processing_duration_seconds:p95:by_type > 5
        for: 5m
        labels:
          severity: warning
          component: postgres-writer
        annotations:
          summary: "Slow processing for {{ $labels.event_type }} events"
          description: "95th percentile processing time for {{ $labels.event_type }} events is {{ $value | humanizeDuration }} (over 5 seconds) for the last 5 minutes."
          runbook_url: "https://github.com/0xIntuition/research-surreal/blob/main/docs/runbooks/slow-event-processing.md"

      # Warning: Cascade processing is slow for a specific event type
      - alert: SlowCascadeProcessing
        expr: postgres_writer:cascade_duration_seconds:p95:by_type > 2
        for: 5m
        labels:
          severity: warning
          component: postgres-writer
        annotations:
          summary: "Slow cascade processing for {{ $labels.event_type }} events"
          description: "95th percentile cascade time for {{ $labels.event_type }} events is {{ $value | humanizeDuration }} (over 2 seconds) for the last 5 minutes. This may indicate database performance issues."
          runbook_url: "https://github.com/0xIntuition/research-surreal/blob/main/docs/runbooks/slow-cascade-processing.md"

      # Info: No events of a specific type have been processed recently
      - alert: NoEventsProcessedForType
        expr: rate(postgres_writer_events_processed_by_type_total[10m]) == 0
        for: 10m
        labels:
          severity: info
          component: postgres-writer
        annotations:
          summary: "No {{ $labels.event_type }} events processed recently"
          description: "No {{ $labels.event_type }} events have been processed in the last 10 minutes. This may be expected if this event type is rare."
          runbook_url: "https://github.com/0xIntuition/research-surreal/blob/main/docs/runbooks/no-events.md"

      # Info: Unusual spike in database operations
      - alert: DatabaseOperationSpike
        expr: |
          postgres_writer:database_operations_rate:by_type
          >
          2 * avg_over_time(postgres_writer:database_operations_rate:by_type[1h])
        for: 5m
        labels:
          severity: info
          component: postgres-writer
        annotations:
          summary: "Spike in {{ $labels.operation }} operations for {{ $labels.event_type }}"
          description: "Database operation rate for {{ $labels.operation }} ({{ $labels.event_type }}) is {{ $value | humanize }} ops/sec, which is 2x the 1-hour average."
          runbook_url: "https://github.com/0xIntuition/research-surreal/blob/main/docs/runbooks/database-spike.md"

  ## PostgreSQL Database Health Alerts
  ## These alerts monitor the PostgreSQL database itself (not just the application)
  - name: postgres_database_alerts
    interval: 15s
    rules:
      # Critical: Connection pool nearly exhausted (postgres-writer application pool)
      - alert: PostgresWriterConnectionPoolExhaustion
        expr: postgres_writer:pool_utilization_percent > 80
        for: 3m
        labels:
          severity: critical
          component: postgres
        annotations:
          summary: "PostgreSQL writer connection pool utilization is critically high"
          description: "Connection pool utilization is {{ $value | humanizePercentage }}. Pool may be exhausted soon, which will cause event processing failures. Consider increasing DATABASE_POOL_SIZE."
          runbook_url: "https://github.com/0xIntuition/research-surreal/blob/main/docs/runbooks/connection-pool-exhaustion.md"

      # Warning: High PostgreSQL connection count (database-wide)
      - alert: PostgresHighConnectionCount
        expr: postgres:connections_utilization_percent > 80
        for: 5m
        labels:
          severity: warning
          component: postgres
        annotations:
          summary: "PostgreSQL connection count is high"
          description: "PostgreSQL is using {{ $value | humanizePercentage }} of max_connections. High connection count may indicate connection leaks or need to increase max_connections setting."
          runbook_url: "https://github.com/0xIntuition/research-surreal/blob/main/docs/runbooks/high-connection-count.md"

      # Warning: Low cache hit ratio - indicates potential performance issues
      - alert: PostgresLowCacheHitRatio
        expr: postgres:cache_hit_ratio_percent < 90
        for: 10m
        labels:
          severity: warning
          component: postgres
        annotations:
          summary: "PostgreSQL cache hit ratio is low"
          description: "Cache hit ratio is {{ $value | humanizePercentage }}, which is below the recommended 90%. This indicates excessive disk I/O. Consider increasing shared_buffers or investigating query patterns."
          runbook_url: "https://github.com/0xIntuition/research-surreal/blob/main/docs/runbooks/low-cache-hit-ratio.md"

      # Warning: Deadlocks detected
      - alert: PostgresDeadlocksDetected
        expr: rate(pg_stat_database_deadlocks{datname="storage"}[5m]) > 0
        for: 2m
        labels:
          severity: warning
          component: postgres
        annotations:
          summary: "PostgreSQL deadlocks detected"
          description: "Deadlocks are occurring at {{ $value | humanize }} per second. Deadlocks indicate transaction conflicts and should be investigated."
          runbook_url: "https://github.com/0xIntuition/research-surreal/blob/main/docs/runbooks/deadlocks.md"

      # Critical: PostgreSQL connection failures
      - alert: PostgresConnectionFailure
        expr: postgres_writer_postgres_healthy == 0
        for: 1m
        labels:
          severity: critical
          component: postgres
        annotations:
          summary: "PostgreSQL connection is unhealthy"
          description: "postgres-writer cannot connect to PostgreSQL database. Event processing is blocked. Check PostgreSQL service status and network connectivity."
          runbook_url: "https://github.com/0xIntuition/research-surreal/blob/main/docs/runbooks/postgres-connection-failure.md"

      # Info: High rollback rate - may indicate application errors
      - alert: PostgresHighRollbackRate
        expr: |
          (
            postgres:transactions_rollback_rate
            /
            postgres:transactions_total_rate
          ) > 0.1
        for: 10m
        labels:
          severity: info
          component: postgres
        annotations:
          summary: "PostgreSQL rollback rate is elevated"
          description: "Transaction rollback rate is {{ $value | humanizePercentage }} of total transactions. High rollback rates may indicate application errors or conflicts."
          runbook_url: "https://github.com/0xIntuition/research-surreal/blob/main/docs/runbooks/high-rollback-rate.md"

      # Warning: Database conflicts detected
      - alert: PostgresConflictsDetected
        expr: rate(pg_stat_database_conflicts{datname="storage"}[5m]) > 0
        for: 5m
        labels:
          severity: warning
          component: postgres
        annotations:
          summary: "PostgreSQL database conflicts detected"
          description: "Database conflicts are occurring at {{ $value | humanize }} per second. This may indicate replication issues or lock contention."
          runbook_url: "https://github.com/0xIntuition/research-surreal/blob/main/docs/runbooks/database-conflicts.md"
