## Recording Rules for PostgreSQL Writer Service
##
## Division-by-Zero Protection Strategy:
##
## Many rules use a dual-protection approach against division by zero:
##
## 1. The "> 0" check in the denominator:
##    Example: (rate(...) + rate(...) > 0)
##    - Returns the sum only if it's greater than zero
##    - If sum is zero, the entire expression returns no value (empty result)
##    - This prevents actual division by zero errors
##
## 2. The "OR" fallback:
##    Example: OR on(event_type) (0 * postgres_writer_events_processed_by_type_total)
##    - Activates when the main expression returns no value
##    - Returns 0 for each event_type that exists in the metrics
##    - Ensures we always have a value to display (either the calculated rate or 0)
##
## Why both are needed:
## - "> 0" protects against division errors
## - "OR" ensures metrics exist even when no events have been processed yet
## - Together, they provide graceful handling during startup and low-traffic periods
##
groups:
  - name: postgres_writer_event_type_recording_rules
    interval: 15s
    rules:
      # Rate metrics - events processed per second by type
      - record: postgres_writer:events_processed_rate:by_type
        expr: rate(postgres_writer_events_processed_by_type_total[5m])

      # Rate metrics - events failed per second by type
      - record: postgres_writer:events_failed_rate:by_type
        expr: rate(postgres_writer_events_failed_by_type_total[5m])

      # Rate metrics - database operations per second by type and operation
      - record: postgres_writer:database_operations_rate:by_type
        expr: rate(postgres_writer_database_operations_total[5m])

      # Rate metrics - database operations per second by operation (summed across types)
      - record: postgres_writer:database_operations_rate:by_operation
        expr: sum by (operation) (rate(postgres_writer_database_operations_total[5m]))

      # Failure rate percentage by type
      - record: postgres_writer:failure_rate_percent:by_type
        expr: |
          100 * (
            rate(postgres_writer_events_failed_by_type_total[5m])
            /
            (rate(postgres_writer_events_processed_by_type_total[5m]) +
             rate(postgres_writer_events_failed_by_type_total[5m]) > 0)
          )
          OR on(event_type) (0 * postgres_writer_events_processed_by_type_total)

      # Success rate percentage by type
      - record: postgres_writer:success_rate_percent:by_type
        expr: |
          100 * (
            rate(postgres_writer_events_processed_by_type_total[5m])
            /
            (rate(postgres_writer_events_processed_by_type_total[5m]) +
             rate(postgres_writer_events_failed_by_type_total[5m]) > 0)
          )
          OR on(event_type) (0 * postgres_writer_events_processed_by_type_total)

      # Cascade overhead percentage by type (cascade time as % of total processing time)
      # Note: This metric can exceed 100% due to concurrent operations or timing variations
      - record: postgres_writer:cascade_overhead_percent:by_type
        expr: |
          100 * (
            rate(postgres_writer_cascade_processing_duration_seconds_sum[5m])
            /
            (rate(postgres_writer_event_processing_duration_by_type_seconds_sum[5m]) > 0)
          )
          OR on(event_type) (0 * postgres_writer_cascade_processing_duration_seconds_sum)

      # Event distribution percentage (what % of all events is each type)
      - record: postgres_writer:event_distribution_percent:by_type
        expr: |
          100 * (
            sum by (event_type) (rate(postgres_writer_events_processed_by_type_total[5m]))
            / ignoring(event_type) group_left
            sum(rate(postgres_writer_events_processed_by_type_total[5m]))
          )

      # Processing duration quantiles by type
      - record: postgres_writer:event_processing_duration_seconds:p50:by_type
        expr: histogram_quantile(0.50, rate(postgres_writer_event_processing_duration_by_type_seconds_bucket[5m]))

      - record: postgres_writer:event_processing_duration_seconds:p95:by_type
        expr: histogram_quantile(0.95, rate(postgres_writer_event_processing_duration_by_type_seconds_bucket[5m]))

      - record: postgres_writer:event_processing_duration_seconds:p99:by_type
        expr: histogram_quantile(0.99, rate(postgres_writer_event_processing_duration_by_type_seconds_bucket[5m]))

      # Average processing duration by type
      - record: postgres_writer:event_processing_duration_seconds:avg:by_type
        expr: |
          rate(postgres_writer_event_processing_duration_by_type_seconds_sum[5m])
          /
          (rate(postgres_writer_event_processing_duration_by_type_seconds_count[5m]) > 0)
          OR on(event_type) (0 * postgres_writer_event_processing_duration_by_type_seconds_sum)

      # Cascade duration quantiles by type
      - record: postgres_writer:cascade_duration_seconds:p50:by_type
        expr: histogram_quantile(0.50, rate(postgres_writer_cascade_processing_duration_seconds_bucket[5m]))

      - record: postgres_writer:cascade_duration_seconds:p95:by_type
        expr: histogram_quantile(0.95, rate(postgres_writer_cascade_processing_duration_seconds_bucket[5m]))

      - record: postgres_writer:cascade_duration_seconds:p99:by_type
        expr: histogram_quantile(0.99, rate(postgres_writer_cascade_processing_duration_seconds_bucket[5m]))

      # Average cascade duration by type
      - record: postgres_writer:cascade_duration_seconds:avg:by_type
        expr: |
          rate(postgres_writer_cascade_processing_duration_seconds_sum[5m])
          /
          (rate(postgres_writer_cascade_processing_duration_seconds_count[5m]) > 0)
          OR on(event_type) (0 * postgres_writer_cascade_processing_duration_seconds_sum)

      # SLO compliance - percentage of events processed under 1 second
      - record: postgres_writer:latency_slo_compliance_percent:by_type
        expr: |
          100 * (
            sum by (event_type) (
              rate(postgres_writer_event_processing_duration_by_type_seconds_bucket{le="1.0"}[5m])
            )
            /
            (sum by (event_type) (
              rate(postgres_writer_event_processing_duration_by_type_seconds_count[5m])
            ) > 0)
          )
          OR on(event_type) (0 * postgres_writer_event_processing_duration_by_type_seconds_count)

      # Hourly metrics - total events processed in last hour by type
      - record: postgres_writer:events_processed_1h:by_type
        expr: increase(postgres_writer_events_processed_by_type_total[1h])

      # Hourly metrics - total events failed in last hour by type
      - record: postgres_writer:events_failed_1h:by_type
        expr: increase(postgres_writer_events_failed_by_type_total[1h])

      # Hourly metrics - peak event processing rate in last hour
      - record: postgres_writer:events_processed_rate_1h_max:by_type
        expr: max_over_time(rate(postgres_writer_events_processed_by_type_total[5m])[1h:1m])

  ## PostgreSQL Database-Level Metrics
  ## These metrics come from postgres_exporter and monitor the PostgreSQL database itself
  - name: postgres_database_recording_rules
    interval: 15s
    rules:
      # Connection pool utilization from postgres-writer application
      - record: postgres_writer:pool_utilization_percent
        expr: postgres_writer_pool_utilization_percent

      - record: postgres_writer:pool_connections_active
        expr: postgres_writer_pool_connections_active

      - record: postgres_writer:pool_connections_idle
        expr: postgres_writer_pool_connections_idle

      # PostgreSQL connection metrics from postgres_exporter
      - record: postgres:connections_active
        expr: pg_stat_database_numbackends{datname="storage"}

      - record: postgres:connections_max
        expr: pg_settings_max_connections

      - record: postgres:connections_utilization_percent
        expr: |
          100 * (
            pg_stat_database_numbackends{datname="storage"}
            /
            pg_settings_max_connections
          )

      # Transaction rates
      - record: postgres:transactions_commit_rate
        expr: rate(pg_stat_database_xact_commit{datname="storage"}[5m])

      - record: postgres:transactions_rollback_rate
        expr: rate(pg_stat_database_xact_rollback{datname="storage"}[5m])

      - record: postgres:transactions_total_rate
        expr: rate(pg_stat_database_xact_commit{datname="storage"}[5m]) + rate(pg_stat_database_xact_rollback{datname="storage"}[5m])

      # Cache hit ratio - percentage of reads served from cache (5m rate)
      # Uses rate() to reflect recent performance rather than all-time stats
      # Includes division-by-zero protection
      - record: postgres:cache_hit_ratio_percent
        expr: |
          100 * (
            sum(rate(pg_stat_database_blks_hit{datname="storage"}[5m]))
            /
            (sum(rate(pg_stat_database_blks_hit{datname="storage"}[5m])) +
             sum(rate(pg_stat_database_blks_read{datname="storage"}[5m])))
          )
          or on() vector(0)

      # Database size growth rate (bytes per second over 1h)
      - record: postgres:database_size_growth_rate
        expr: rate(pg_database_size_bytes{datname="storage"}[1h])

      # Tuple (row) operation rates
      - record: postgres:tuples_inserted_rate
        expr: rate(pg_stat_database_tup_inserted{datname="storage"}[5m])

      - record: postgres:tuples_updated_rate
        expr: rate(pg_stat_database_tup_updated{datname="storage"}[5m])

      - record: postgres:tuples_deleted_rate
        expr: rate(pg_stat_database_tup_deleted{datname="storage"}[5m])

      - record: postgres:tuples_fetched_rate
        expr: rate(pg_stat_database_tup_fetched{datname="storage"}[5m])

      # Deadlock rate
      - record: postgres:deadlocks_rate
        expr: rate(pg_stat_database_deadlocks{datname="storage"}[5m])

      # Lock wait events rate
      - record: postgres:conflicts_rate
        expr: rate(pg_stat_database_conflicts{datname="storage"}[5m])
