name: Monitoring Configuration Validation

on:
  pull_request:
    paths:
      - "infrastructure/monitoring/**"
      - ".github/workflows/monitoring-validation.yml"
  push:
    branches:
      - main
    paths:
      - "infrastructure/monitoring/**"

jobs:
  validate-prometheus-configs:
    name: Validate Prometheus Configuration Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download promtool
        run: |
          PROMETHEUS_VERSION="2.47.0"
          wget https://github.com/prometheus/prometheus/releases/download/v${PROMETHEUS_VERSION}/prometheus-${PROMETHEUS_VERSION}.linux-amd64.tar.gz
          tar xzf prometheus-${PROMETHEUS_VERSION}.linux-amd64.tar.gz
          sudo mv prometheus-${PROMETHEUS_VERSION}.linux-amd64/promtool /usr/local/bin/
          promtool --version

      - name: Validate Prometheus configuration
        run: |
          promtool check config infrastructure/monitoring/prometheus.yml

      - name: Validate alert rules
        run: |
          promtool check rules infrastructure/monitoring/alert_rules.yml

      - name: Validate recording rules
        run: |
          promtool check rules infrastructure/monitoring/recording_rules.yml

      - name: Test alert rule queries
        run: |
          echo "✅ Alert rules syntax validation passed"
          echo "Note: Query evaluation against actual metrics requires a running Prometheus instance"

      - name: Validation Summary
        if: success()
        run: |
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "✅ All Prometheus configuration files validated successfully"
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo ""
          echo "Validated files:"
          echo "  • prometheus.yml      - Main Prometheus configuration"
          echo "  • alert_rules.yml     - Alert rule definitions"
          echo "  • recording_rules.yml - Recording rule definitions"
          echo ""
          echo "These configurations are ready for deployment."
